/**
 * 🗺️ خريطة العناوين المعيارية لشاشات ومسارات النظام
 * TriPro ERP — utils/routeTitles.ts
 * 
 * توفر أسماء الشاشات باللغة العربية لكل مسار في النظام لتغذية:
 * 1. شريط العنوان العلوي (Header)
 * 2. الوصول السريع بالقائمة الجانبية (Sidebar Quick Access)
 * 3. عنوان نافذة المتصفح (Document Title) وسجل التنقل
 */

export const ROUTE_TITLES: Record<string, string> = {
  // 📊 لوحات القيادة والعامة
  '/': 'لوحة القيادة والتحكم الرئيسية',
  '/dashboard': 'لوحة القيادة والتحكم الرئيسية',
  '/cfo-dashboard': 'لوحة قيادة المدير المالي (CFO)',
  '/financial-ratios': 'التحليل المالي ومؤشرات الأداء',
  '/about': 'حول نظام TriPro ERP',
  '/profile': 'الملف الشخصي وإعدادات الحساب',
  '/login': 'تسجيل الدخول للنظام',
  '/admin/test-dashboard': 'لوحة الفحص والتشخيص الإداري',
  '/admin/audit-logs': 'مركز الحوكمة والأركان المالية الأربعة',
  '/mobile': 'تطبيق الموبايل الميداني (PWA Companion)',
  '/user-guide': 'دليل استخدام النظام والمساعدة',

  // 📈 المبيعات والعملاء
  '/sales': 'سجل فواتير المبيعات',
  '/sales-invoice': 'فاتورة مبيعات جديدة',
  '/invoices-list': 'سجل فواتير المبيعات',
  '/eta-invoices': 'الفاتورة والإيصال الإلكتروني (منظومة الضرائب المصرية ETA)',
  '/recurring-invoices': 'الفواتير الدورية والاشتراكات المجدولة',
  '/quotations-new': 'إنشاء عرض سعر جديد',
  '/quotations-list': 'سجل عروض الأسعار',
  '/sales-order-new': 'أمر بيع وتعميد جديد',
  '/sales-orders': 'سجل أوامر البيع والتعميد',
  '/sales-return': 'تسجيل مرتجع مبيعات',
  '/sales-returns-list': 'سجل مرتجعات المبيعات',
  '/free-returns-report': 'تقرير المرتجعات الحرة (بدون فاتورة أصلية)',
  '/credit-note': 'إنشاء إشعار دائن جديد',
  '/credit-notes-list': 'سجل الإشعارات الدائنة',
  '/offer-beneficiaries': 'تقرير المستفيدين من العروض الترويجية',
  '/customers': 'إدارة حسابات وبيانات العملاء',
  '/customer-statement': 'كشف حساب عميل تفصيلي',
  '/customer-reconciliation': 'مطابقة ومصادقة أرصدة العملاء',
  '/customer-aging': 'تقرير أعمار ديون العملاء',
  '/item-sales-analysis': 'تحليل مبيعات وربحية الأصناف',
  '/reports/sales-by-user': 'تقرير مبيعات الكاشير والمستخدمين',
  '/sales-reports': 'مركز تقارير المبيعات الشاملة',

  // 🛒 المشتريات والموردين
  '/purchases': 'سجل فواتير المشتريات',
  '/purchases/rfq': 'طلبات عروض الأسعار والمناقصات (RFQ)',
  '/purchase-invoice': 'فاتورة مشتريات جديدة',
  '/purchase-invoices-list': 'سجل فواتير المشتريات',
  '/purchase-order-new': 'أمر شراء جديد للمورد',
  '/purchase-order-list': 'سجل أوامر الشراء',
  '/purchases/auto-reorder': 'أوامر الشراء التلقائية (حد الأمان)',
  '/purchase-return': 'تسجيل مرتجع مشتريات',
  '/purchase-returns-list': 'سجل مرتجعات المشتريات',
  '/debit-note': 'إنشاء إشعار مدين للمورد',
  '/debit-notes-list': 'سجل الإشعارات المدينة للموردين',
  '/net-purchases-report': 'تقرير صافي المشتريات والخصومات',
  '/supplier-reconciliation': 'مطابقة ومصادقة أرصدة الموردين',
  '/supplier-balances': 'تقرير أرصدة الموردين الإجمالية',
  '/suppliers': 'إدارة حسابات وبيانات الموردين',
  '/supplier-statement': 'كشف حساب مورد تفصيلي',
  '/supplier-aging': 'تقرير أعمار ديون الموردين',
  '/purchases/vendor-contracts': 'عقود الموردين وحوافز البوانص (Rebates)',
  '/vendor-contracts': 'عقود الموردين وحوافز البوانص (Rebates)',
  '/purchase-analysis': 'تحليل المشتريات وسلاسل الإمداد',
  '/purchase-reports': 'مركز تقارير المشتريات الشاملة',

  // 📦 المخازن وإدارة المخزون
  '/products': 'دليل الأصناف والمنتجات والخدمات',
  '/warehouses': 'إدارة المستودعات والمخازن والفروع',
  '/inventory-dashboard': 'لوحة قيادة إدارة المخزون والمستودعات',
  '/opening-inventory': 'تسجيل بضاعة أول المدة والأرصدة الافتتاحية',
  '/inventory/goods-receipt': 'محاضر الفحص والاستلام المخزني',
  '/goods-receipt': 'محاضر الفحص والاستلام المخزني',
  '/inventory/pda-stocktaking': 'الجرد الميداني بالأجهزة الكفية (PDA)',
  '/pda-stocktaking': 'الجرد الميداني بالأجهزة الكفية (PDA)',
  '/inventory/expiry-radar': 'رادار متابعة تواريخ الصلاحية والتنبيهات',
  '/expiry-radar': 'رادار متابعة تواريخ الصلاحية والتنبيهات',
  '/inventory/shelf-restock': 'تقرير إعادة ملء الأرفف ونقاط البيع',
  '/shelf-restock': 'تقرير إعادة ملء الأرفف ونقاط البيع',
  '/inventory/replenishment': 'التغذية التلقائية للمخازن والفروع',
  '/replenishment': 'التغذية التلقائية للمخازن والفروع',
  '/inventory/bin-locations': 'إدارة مواقع التخزين وعناوين الأرفف (WMS)',
  '/inventory/bins': 'إدارة مواقع التخزين وعناوين الأرفف (WMS)',
  '/inventory/in-transit': 'البضاعة المحولة والواردة بالطريق',
  '/inventory/in-transit-transfers': 'البضاعة المحولة والواردة بالطريق',
  '/inventory-transfer': 'التحويل المخزني بين المستودعات',
  '/stock-transfer': 'التحويل المخزني بين المستودعات',
  '/inventory-transfers-list': 'سجل تحويلات البضاعة بين المخازن',
  '/stock-transfer-list': 'سجل تحويلات البضاعة بين المخازن',
  '/inventory-count': 'الجرد المخزني وتسوية الفروقات',
  '/inventory-history': 'سجل عمليات وأرشيف الجرد المخزني',
  '/inventory-adjustments-list': 'سجل تسويات الجرد المخزني',
  '/stock-adjustment': 'تسوية فروقات الجرد المخزني',
  '/warehouse-items': 'تقرير أرصدة المخازن التفصيلي',
  '/wastage': 'إدارة الهوالك والتالف المخزني',
  '/wastage-report': 'تقرير الهوالك والتالف المخزني',
  '/inventory-revaluation': 'إعادة تقييم المخزون المالي',
  '/stock-card': 'بطاقة حركة صنف (أستاذ المخزن)',
  '/item-movement': 'تقرير حركة صنف تفصيلي',
  '/stock-movement-cost': 'تقرير تكلفة حركات المخزون التفصيلية',
  '/detailed-stock-movement': 'تقرير حركة المخزون الشامل واليوميات المخزنية',
  '/reorder-levels': 'مراقبة حد إعادة الطلب ونواقص المخزون',
  '/slow-moving': 'تقرير الأصناف الراكدة وبطيئة الحركة',
  '/top-selling': 'تقرير الأصناف الأكثر مبيعاً ورواجاً',
  '/item-profit': 'تقرير ربحية الأصناف وهامش الربح',
  '/inventory-valuation': 'تقييم المخزون المالي (متوسط التكلفة WAC)',
  '/units-of-measure': 'وحدات القياس والتحويلات المعيارية',
  '/multi-uom-report': 'تقرير أرصدة المخزون بالوحدات المتعددة',

  // 🏛️ المحاسبة العامة والتقارير المالية
  '/accounting-dashboard': 'لوحة القيادة والمؤشرات المحاسبية',
  '/general-journal': 'دفتر اليومية العامة',
  '/journal': 'تسجيل قيد يومية يدوي جديد',
  '/journal-entry': 'تسجيل قيد يومية يدوي جديد',
  '/draft-journals': 'القيود المحاسبية المسودة (غير المرحلة)',
  '/accounts': 'دليل الحسابات المالي الشامل (COA)',
  '/ledger': 'دفتر الأستاذ العام',
  '/trial-balance': 'ميزان المراجعة المتقدم بالمجاميع والأرصدة',
  '/trial-balance-advanced': 'ميزان المراجعة المتقدم بالمجاميع والأرصدة',
  '/income-statement': 'قائمة الدخل الشامل (IFRS 18)',
  '/balance-sheet': 'قائمة المركز المالي والميزانية العمومية',
  '/changes-in-equity': 'قائمة التغير في حقوق الملكية',
  '/cash-flow': 'قائمة التدفقات النقدية المعيارية',
  '/cash-flow-statement': 'قائمة التدفقات النقدية المعيارية',
  '/cash-flow-report': 'تقرير التدفقات النقدية المقارن',
  '/annual-report': 'كتاب التقرير المالي السنوي الموحد (IAS 1)',
  '/budget-manager': 'إدارة الموازنات التقديرية والتخطيط المالي',
  '/budget-setup': 'إدارة الموازنات التقديرية والتخطيط المالي',
  '/budget-variance': 'تقرير انحرافات ومقارنة الموازنة التقديرية',
  '/budget-report': 'تقرير انحرافات ومقارنة الموازنة التقديرية',
  '/accounting/fiscal-closing': 'الإقفال المالي السنوي وترحيل الأرباح',
  '/fiscal-year-closing': 'الإقفال المالي السنوي وترحيل الأرباح',
  '/accounting/fiscal-periods': 'إدارة وقفل الفترات المحاسبية',
  '/fiscal-periods': 'إدارة وقفل الفترات المحاسبية',
  '/accounting/export': 'تصدير وأرشفة القيود اليومية المحاسبية',
  '/journal-export': 'تصدير وأرشفة القيود اليومية المحاسبية',
  '/assets': 'إدارة الأصول الثابتة وإهلاكها',
  '/tax-return': 'إقرار ضريبة القيمة المضافة والأرباح التجارية',
  '/performance-comparison': 'تقرير مقارنة الأداء المالي متعدد الفترات',
  '/multi-currency-statement': 'كشف الحساب متعدد العملات وفروق الصرف',
  '/payment-method-report': 'تقرير حركات المبيعات حسب طرق الدفع',
  '/attachments-report': 'سجل وأرشيف المرفقات والوثائق المؤيدة',
  '/important-reports': 'دليل التقارير المالية والإدارية الهامة',
  '/expense-analysis': 'تحليل المصروفات والبنود التكاليفية',

  // 🏦 النقدية والبنوك والشيكات
  '/treasury': 'إدارة الخزائن النقدية والصناديق',
  '/bank-accounts': 'الحسابات المصرفية والأرصدة البنكية',
  '/vouchers': 'سجل سندات القبض والصرف',
  '/receipt-voucher': 'سند قبض نقدي / بنكي',
  '/receipt-vouchers-list': 'سجل سندات القبض',
  '/payment-voucher': 'سند صرف نقدي / بنكي',
  '/payment-vouchers-list': 'سجل سندات الصرف',
  '/expense-voucher': 'سند صرف مصروفات تشغيلية',
  '/transfer': 'التحويل المالي بين الخزائن والبنوك',
  '/customer-deposit': 'استلام دفعات وتأمينات العملاء المقدمة',
  '/petty-cash': 'العهد النقدية والمصاريف النثرية',
  '/petty-cash-list': 'سجل تسويات العهد النقدية',
  '/cheques': 'إدارة وحافظة الشيكات (الواردة والصادرة)',
  '/incoming-cheques': 'حافظة الشيكات الواردة (تحت التحصيل)',
  '/outgoing-cheques': 'حافظة الشيكات الصادرة (أوراق الدفع)',
  '/bank-reconciliation': 'مذكرة التسوية البنكية ومطابقة الحساب',
  '/cash-shifts': 'ورديات الصناديق وتقفيل الكاش',
  '/cash-closing': 'ورديات الصناديق وتقفيل الكاش',
  '/banking/cheque-movement': 'تقرير مسار ودورة حياة الشيكات',
  '/cheque-movement-report': 'تقرير مسار ودورة حياة الشيكات',
  '/banking/returned-cheques': 'تقرير الشيكات المرتدة والمرفوضة',
  '/returned-cheques-report': 'تقرير الشيكات المرتدة والمرفوضة',
  '/letters-of-credit': 'إدارة الاعتمادات المستندية (LC)',
  '/letters-of-guarantee': 'إدارة خطابات الضمان المصرفية (LG)',
  '/payment-gateways': 'إعدادات بوابات الدفع الإلكتروني والمدفوعات',
  '/deficit-report': 'تقرير عجز وفائض الخزائن النقدية',

  // 👥 الموارد البشرية والرواتب (HR)
  '/hr': 'لوحة قيادة الموارد البشرية',
  '/hr/dashboard': 'لوحة قيادة الموارد البشرية',
  '/employees': 'دليل وسجلات الموظفين',
  '/hr/employees': 'دليل وسجلات الموظفين',
  '/payroll-run': 'مسير ومسيرات الرواتب الشهرية',
  '/hr/payroll': 'مسير ومسيرات الرواتب الشهرية',
  '/employee-advances': 'السلف النقدية والقروض الشخصية للموظفين',
  '/hr/advances': 'السلف النقدية والقروض الشخصية للموظفين',
  '/hr/leaves': 'إدارة الإجازات والأذونات والغياب',
  '/hr/attendance': 'سجل الحضور والانصراف والبصمات',
  '/hr/biometrics': 'ربط ومزامنة أجهزة البصمة الذكية',
  '/hr/shifts': 'إدارة الورديات وتوزيع جداول العمل',
  '/hr/penalties': 'لائحة الجزاءات والمكافآت التقديرية',
  '/hr/penalties-rewards': 'لائحة الجزاءات والمكافآت التقديرية',
  '/hr/end-of-service': 'احتساب مكافأة نهاية الخدمة والمستحقات',
  '/payroll-report': 'تقرير تحليلي لمسيرات الرواتب والبدلات',
  '/hr/reports/payroll': 'تقرير تحليلي لمسيرات الرواتب والبدلات',
  '/employee-statement': 'كشف حساب واستحقاقات موظف',
  '/hr/reports/statement': 'كشف حساب واستحقاقات موظف',
  '/employee-reports': 'تقارير الموارد البشرية وشؤون الموظفين',
  '/hr/reports/general': 'تقارير الموارد البشرية وشؤون الموظفين',

  // 🏭 التصنيع والإنتاج وقوائم المواد
  '/manufacturing': 'لوحة قيادة التصنيع ومؤشرات الإنتاج',
  '/manufacturing/dashboard': 'لوحة قيادة التصنيع ومؤشرات الإنتاج',
  '/mfg/dashboard': 'لوحة قيادة التصنيع ومؤشرات الإنتاج',
  '/manufacturing/work-orders': 'أوامر الشغل وأوامر الإنتاج (Work Orders)',
  '/mfg/orders': 'أوامر الشغل وأوامر الإنتاج (Work Orders)',
  '/manufacturing/batch-orders': 'أوامر التشغيل وتتبع الدفعات (Batches)',
  '/mfg/batch-orders': 'أوامر التشغيل وتتبع الدفعات (Batches)',
  '/manufacturing/shop-floor': 'صالة التصنيع وتتبع خطوط الإنتاج (Shop Floor)',
  '/mfg/shop-floor': 'صالة التصنيع وتتبع خطوط الإنتاج (Shop Floor)',
  '/manufacturing/qc': 'مراقبة الجودة وفحص العينات (QC)',
  '/manufacturing/quality-control': 'مراقبة الجودة وفحص العينات (QC)',
  '/mfg/quality-control': 'مراقبة الجودة وفحص العينات (QC)',
  '/manufacturing/bom': 'قوائم المواد ومراحل التصنيع (BOM & Routing)',
  '/mfg/routing-bom': 'قوائم المواد ومراحل التصنيع (BOM & Routing)',
  '/manufacturing/material-requests': 'أذون طلب وصرف خامات التصنيع',
  '/mfg/material-requests': 'أذون طلب وصرف خامات التصنيع',
  '/manufacturing/oee': 'الكفاءة الشاملة للمعدات والماكينات (OEE)',
  '/mfg/oee-tracker': 'الكفاءة الشاملة للمعدات والماكينات (OEE)',
  '/manufacturing/maintenance': 'صيانة الماكينات وخطوط الإنتاج الوقائية',
  '/mfg/maintenance': 'صيانة الماكينات وخطوط الإنتاج الوقائية',
  '/manufacturing/capacity': 'تخطيط الطاقة الإنتاجية والتحميل',
  '/mfg/capacity-planning': 'تخطيط الطاقة الإنتاجية والتحميل',
  '/manufacturing/gantt': 'مخطط جانت الزمني للجدولة الإنتاجية',
  '/mfg/gantt-schedule': 'مخطط جانت الزمني للجدولة الإنتاجية',
  '/manufacturing/cost-closing': 'تقفيل وتوزيع تكاليف التشغيل الصناعية',
  '/mfg/closing': 'تقفيل وتوزيع تكاليف التشغيل الصناعية',
  '/manufacturing/reports/cost-analysis': 'تحليل تكاليف أوامر الإنتاج والتكاليف الإضافية',
  '/mfg/production-cost-analysis': 'تحليل تكاليف أوامر الإنتاج والتكاليف الإضافية',
  '/manufacturing/reports/unit-cost': 'تحليل تكلفة الوحدة المنتجة',
  '/mfg/unit-cost-drilldown': 'تحليل تكلفة الوحدة المنتجة',
  '/manufacturing/reports/bom-variance': 'تقرير انحرافات استهلاك الخامات المعيارية (BOM Variance)',
  '/mfg/variance-report': 'تقرير انحرافات استهلاك الخامات المعيارية (BOM Variance)',
  '/manufacturing/reports/genealogy': 'شجرة التتبع والأصل الوراثي للدفعات (Batch Genealogy)',
  '/mfg/genealogy': 'شجرة التتبع والأصل الوراثي للدفعات (Batch Genealogy)',
  '/manufacturing/reports/profitability': 'تقرير ربحية خطوط الإنتاج والمنتجات المصنعة',
  '/mfg/profitability': 'تقرير ربحية خطوط الإنتاج والمنتجات المصنعة',
  '/manufacturing/reports/raw-turnover': 'معدل دوران المواد الخام والمستلزمات',
  '/mfg/raw-materials-turnover': 'معدل دوران المواد الخام والمستلزمات',
  '/manufacturing/reports/wip': 'تقرير الإنتاج تحت التشغيل الشهري (WIP)',
  '/mfg/wip-monthly-summary': 'تقرير الإنتاج تحت التشغيل الشهري (WIP)',
  '/manufacturing/alerts': 'سجل إنذارات ومخاطر خطوط الإنتاج',
  '/mfg/alerts-log': 'سجل إنذارات ومخاطر خطوط الإنتاج',

  // 🍽️ المطاعم والمطابخ والكافيهات
  '/pos': 'نقطة بيع المطاعم السريعة (POS)',
  '/restaurant/pos': 'نقطة بيع المطاعم السريعة (POS)',
  '/kds': 'شاشة عرض المطبخ الذكية (KDS)',
  '/restaurant/kds': 'شاشة عرض المطبخ الذكية (KDS)',
  '/expo': 'شاشة مراقب ومجهز الطلبات (Expo)',
  '/restaurant/expo': 'شاشة مراقب ومجهز الطلبات (Expo)',
  '/waiter': 'تطبيق الويتر المحمول لأخذ الطلبات',
  '/restaurant/waiter': 'تطبيق الويتر المحمول لأخذ الطلبات',
  '/customer-display': 'شاشة عرض العميل المقابلة (Customer Display)',
  '/restaurant/customer-display': 'شاشة عرض العميل المقابلة (Customer Display)',
  '/kiosk': 'كشك الطلب الذاتي للعملاء (Self-Ordering Kiosk)',
  '/restaurant/kiosk': 'كشك الطلب الذاتي للعملاء (Self-Ordering Kiosk)',
  '/kitchen-stations': 'توجيه طلبات محطات المطبخ والأقسام',
  '/restaurant/stations': 'توجيه طلبات محطات المطبخ والأقسام',
  '/printers': 'إدارة الطابعات الحرارية وطابعات البونات',
  '/restaurant/printers': 'إدارة الطابعات الحرارية وطابعات البونات',
  '/driver-dispatch': 'شاشة تتبع وتوجيه طياري التوصيل (Dispatch)',
  '/restaurant/driver-dispatch': 'شاشة تتبع وتوجيه طياري التوصيل (Dispatch)',
  '/aggregators': 'ربط تطبيقات التوصيل والمنصات الخارجية (Aggregators)',
  '/restaurant/aggregators': 'ربط تطبيقات التوصيل والمنصات الخارجية (Aggregators)',
  '/happy-hours': 'عروض الساعات السعيدة والتسعير الزمني',
  '/restaurant/happy-hours': 'عروض الساعات السعيدة والتسعير الزمني',
  '/channel-pricing': 'التسعير المتعدد حسب قنوات البيع',
  '/restaurant/channel-pricing': 'التسعير المتعدد حسب قنوات البيع',
  '/loyalty': 'برنامج ولاء ونقاط العملاء',
  '/restaurant/loyalty': 'برنامج ولاء ونقاط العملاء',
  '/tips-pool': 'تجميع وتوزيع بقشيش العاملين (Tips Pool)',
  '/restaurant/tips-pool': 'تجميع وتوزيع بقشيش العاملين (Tips Pool)',
  '/win-back': 'حملات استعادة العملاء المتغيبين (Win-Back)',
  '/restaurant/win-back': 'حملات استعادة العملاء المتغيبين (Win-Back)',
  '/auto-reorder': 'إعادة الطلب التلقائي لمستلزمات المطبخ',
  '/restaurant/auto-reorder': 'إعادة الطلب التلقائي لمستلزمات المطبخ',
  '/butchering-yield': 'معدل تصافي اللحوم والتقطيع (Butchering Yield)',
  '/restaurant/butchering-yield': 'معدل تصافي اللحوم والتقطيع (Butchering Yield)',
  '/menu': 'قائمة الطعام الرقمية (Digital QR Menu)',
  '/restaurant/menu': 'قائمة الطعام الرقمية (Digital QR Menu)',
  '/kitchen-end-day': 'الجرد اليومي وتقفيل مستلزمات المطبخ',
  '/reports/restaurant-sales': 'تقرير مبيعات المطعم التفصيلي والورديات',
  '/restaurant/reports/sales': 'تقرير مبيعات المطعم التفصيلي والورديات',
  '/reports/wastage-analysis': 'تقرير هوالك وإهدار المطبخ والوجبات',
  '/restaurant/reports/wastage': 'تقرير هوالك وإهدار المطبخ والوجبات',
  '/reports/restaurant-profit': 'تقرير ربحية قائمة الطعام والأطباق',
  '/restaurant/reports/profit': 'تقرير ربحية قائمة الطعام والأطباق',
  '/restaurant-analytics': 'تحليلات ذكاء أعمال المطاعم ومؤشرات الذروة',
  '/restaurant/analytics': 'تحليلات ذكاء أعمال المطاعم ومؤشرات الذروة',

  // 🛒 التجزئة والهايبر ماركت (Retail POS)
  '/retail-pos': 'نقطة بيع التجزئة والباركود المباشر (Retail POS)',
  '/retail/pos': 'نقطة بيع التجزئة والباركود المباشر (Retail POS)',
  '/price-checker': 'كشك استعلام الأسعار للجمهور (Price Checker)',
  '/retail/price-checker': 'كشك استعلام الأسعار للجمهور (Price Checker)',
  '/retail/customer-display': 'شاشة عرض العميل المقابلة (Retail Display)',
  '/promotions': 'عروض وتخفيضات التجزئة المتقدمة',
  '/retail/promotions': 'عروض وتخفيضات التجزئة المتقدمة',

  // 🏗️ المقاولات وإدارة المشاريع الإنشائية
  '/construction': 'إدارة المشاريع الإنشائية ومواقع العمل',
  '/construction/dashboard': 'لوحة قيادة قطاع المقاولات والمشاريع',
  '/construction/projects': 'إدارة المشاريع الإنشائية ومواقع العمل',
  '/construction/analytics': 'لوحة تحليلات وذكاء أعمال المقاولات',
  '/construction/labor-reports': 'تقرير تكلفة العمالة المباشرة والميدانية',
  '/construction/site-logs': 'اليوميات وسجلات الموقع اليومية',
  '/construction/daily-logs': 'اليوميات وسجلات الموقع اليومية',
  '/construction/rfis-submittals': 'طلبات المعلومات والاستفسارات الفنية (RFI)',
  '/construction/rfi': 'طلبات المعلومات والاستفسارات الفنية (RFI)',
  '/construction/inspections': 'محاضر استلام الأعمال والفحص الهندسي',
  '/construction/waste-analytics': 'تحليل فاقد وهدر مواد البناء بالموقع',
  '/construction/price-escalation': 'حاسبة فروق الأسعار وتعديل تكاليف العقود',
  '/construction/escalation': 'حاسبة فروق الأسعار وتعديل تكاليف العقود',
  '/subcontractors': 'إدارة مقاولي الباطن ومستخلصات الأعمال',
  '/construction/subcontractors': 'إدارة مقاولي الباطن ومستخلصات الأعمال',
  '/construction/subcontractor-analytics': 'تحليلات أداء عقود ومستخلصات مقاولي الباطن',
  '/construction/reports/labor': 'تقرير تكلفة العمالة المباشرة والميدانية',
  '/construction/reports/analytics': 'تحليلات أداء عقود ومستخلصات مقاولي الباطن',

  // 🏥 المنظومة الطبية والمستشفيات (HIMS)
  '/hims': 'دليل وسجلات المرضى (الملف الطبي)',
  '/hims/dashboard': 'لوحة قيادة المنظومة الطبية والمستشفيات',
  '/hims/admin': 'التقرير الإحصائي والتنفيذي لإدارة المستشفى',
  '/hims/patients': 'سجل وبيانات المرضى (الملف الطبي الموحد)',
  '/hims/doctor-desktop': 'المحطة الإكلينيكية للطبيب المعالج',
  '/hims/doctor-kpis': 'مؤشرات الأداء السريري والإكلينيكي للأطباء',
  '/hims/doctors': 'دليل الأطباء والاستشاريين',
  '/hims/appointments': 'جدول المواعيد والعيادات الخارجية',
  '/hims/billing': 'الفواتير والمطالبات الطبية',
  '/hims/insurance-claims': 'إدارة مطالبات وشركات التأمين الصحي',
  '/hims/insurance': 'إدارة شركات التأمين والتعاقدات الطبية',
  '/hims/lab': 'المختبر ومعامل التحاليل الطبية',
  '/hims/lab/tracking': 'تتبع العينات المخبرية ونتائج الفحص',
  '/hims/lab-tracking': 'تتبع العينات المخبرية ونتائج الفحص',
  '/hims/blood-bank': 'إدارة بنك الدم ومشتقاته',
  '/hims/radiology': 'قسم الأشعة والتصوير الطبي',
  '/hims/nurse-station': 'محطة التمريض ومتابعة المرضى',
  '/hims/nursing': 'محطة التمريض ومتابعة المرضى',
  '/hims/er': 'لوحة فرز واستقبال طوارئ المستشفى (ER Triage)',
  '/hims/er-triage': 'لوحة فرز واستقبال طوارئ المستشفى (ER Triage)',
  '/hims/pharmacy': 'الصيدلية الداخلية وصرف الروشتات',
  '/hims/admissions': 'الدخول والتنويم الداخلي',
  '/hims/inpatient-board': 'لوحة متابعة المرضى المنومين بالأقسام',
  '/hims/wards': 'إدارة الأجنحة والغرف وتسكين الأسِرّة',
  '/hims/wards-management': 'إدارة الأجنحة والغرف وتسكين الأسِرّة',
  '/hims/surgeries': 'جدولة العمليات وغرف الجراحة المجهزة',
  '/hims/operating-theater': 'إدارة غرف العمليات والتدخل الجراحي',
  '/hims/staff-roster': 'نوبتجيات وجداول الفريق الطبي والتمريض',
  '/hims/services': 'دليل الخدمات الطبية ولائحة الأسعار',
  '/hims/profitability': 'تقرير ربحية الخدمات والأقسام الطبية',
  '/hims/reports/executive': 'التقرير الإحصائي والتنفيذي لإدارة المستشفى',
  '/hims/reports/profitability': 'تقرير ربحية الخدمات والأقسام الطبية',

  // 🏟️ إدارة الأندية والاستادات والمنشآت الرياضية
  '/stadium': 'لوحة قيادة إدارة الاستاد والمنشآت الرياضية',
  '/stadium/dashboard': 'لوحة قيادة إدارة الاستاد والمنشآت الرياضية',
  '/stadium/gate-scanner': 'بوابات الدخول والمسح الإلكتروني للتذاكر',
  '/stadium/members': 'عضويات واشتراكات النادي الرياضي',
  '/stadium/facilities': 'الملاعب والصالات والمرافق الرياضية',
  '/stadium/maintenance': 'صيانة الملاعب والنجيلة والمنشآت',
  '/stadium/bookings': 'حجوزات الملاعب والفعاليات الرياضية',
  '/stadium/rentals': 'تأجير المعدات والمرافق والمساحات',
  '/stadium/programs': 'الأكاديميات والبرامج التدريبية',
  '/stadium/tournaments': 'إدارة الدوريات والبطولات والمنافسات',
  '/stadium/coaches': 'سجل المدربين والكوادر الفنية',
  '/stadium/budget': 'موازنة ومصروفات الاستاد التقديرية',
  '/stadium/disbursements': 'أذون الصرف والمستحقات الرياضية',
  '/stadium/custodies': 'سجل العهد والأدوات الرياضية والمعدات',
  '/stadium/custody': 'سجل العهد والأدوات الرياضية والمعدات',
  '/stadium/reports/revenue': 'تقرير إيرادات الاستاد والأنشطة الرياضية',
  '/stadium/reports/expenses': 'تقرير مصروفات وتكاليف تشغيل الاستاد',
  '/stadium/reports/expense': 'تقرير مصروفات وتكاليف تشغيل الاستاد',
  '/stadium/reports/pnl': 'قائمة الأرباح والخسائر للقطاع الرياضي',
  '/stadium/reports/occupancy': 'تقرير نسب إشغال الملاعب والمرافق',
  '/stadium/reports/member-aging': 'تقرير أعمار مديونيات الأعضاء والاشتراكات',
  '/stadium/reports/program-profit': 'تقرير ربحية الأكاديميات والأنشطة الرياضية',

  // ⚙️ إعدادات النظام والأمان والأدوات الإدارية
  '/settings': 'إعدادات المنشأة العامة وتفضيلات النظام',
  '/settings/users': 'إدارة المستخدمين والصلاحيات والوصول',
  '/users': 'إدارة المستخدمين والموظفين المصرح لهم',
  '/settings/roles': 'إدارة الأدوار والمجموعات الوظيفية',
  '/permissions': 'مصفوفة الصلاحيات والأدوار المتقدمة',
  '/settings/security': 'مركز الأمان والمراقبة والنسخ الاحتياطي',
  '/security-logs': 'سجل الأمان ومحاولات الدخول والجلسات',
  '/settings/company': 'بيانات الشركة والترويسة والرقم الضريبي',
  '/settings/accounting': 'التوجيه المحاسبي وربط الحسابات التلقائي',
  '/settings/print': 'تنسيق قوالب وتصميمات الطباعة',
  '/saas-admin': 'لوحة إدارة النظام السحابي والشركات (SaaS)',
  '/recycle-bin': 'سلة المحذوفات واستعادة البيانات',
  '/data-migration': 'مركز ترحيل واستيراد البيانات',
  '/stress-test': 'فحص الإجهاد وتحمل الخوادم وقواعد البيانات',
};

/**
 * دالة مساعدة لجلب عنوان المسار مع دعم المعلمات الديناميكية
 */
export function getRouteTitle(pathname: string): string {
  // 1. تنظيف المسار من المعلمات الزائدة والـ query string والـ trailing slash
  const cleanPath = pathname.split('?')[0].split('#')[0].replace(/\/+$/, '') || '/';

  // 2. مطابقة مباشرة
  if (ROUTE_TITLES[cleanPath]) {
    return ROUTE_TITLES[cleanPath];
  }

  // 3. مطابقة جزئية للمسارات التابعة أو التي تحتوي على معرفات ديناميكية مثل /public/... أو /items/:id
  for (const [route, title] of Object.entries(ROUTE_TITLES)) {
    if (route !== '/' && (cleanPath === route || cleanPath.startsWith(route + '/'))) {
      return title;
    }
  }

  return 'نظام TriPro ERP المؤسسي المتكامل';
}
